version: "3.9"
services:
  biblivre:
    image: faelcavalheri/biblivre5-docker:latest
    container_name: biblivre
    ports:
      - "9050:8080"
    environment:
      - TZ=America/Sao_Paulo
      - JAVA_TOOL_OPTIONS=-Duser.timezone=GMT-03:00 -Duser.country=BR -Duser.language=pt
    volumes:
      - ./setenv.sh:/usr/local/tomcat/bin/setenv.sh:ro
      - /dados/biblivre-db:/var/lib/postgresql/9.6/main
      - ./webapps:/usr/local/tomcat/webapps
    restart: unless-stopped
