version: "3.9"
services:
  biblivre:
    build: .
    image: biblivre-local:latest
    container_name: biblivre
    ports:
      - "9050:8080"
    environment:
      - POSTGRES_USER=biblivre
      - POSTGRES_PASSWORD=abracadabra
      - POSTGRES_DB=biblivre4
      - TZ=America/Sao_Paulo
      - JAVA_TOOL_OPTIONS=-Duser.timezone=GMT-03:00 -Duser.country=BR -Duser.language=pt
    entrypoint: ["/bin/bash", "/start_biblivre.sh"]
    volumes:
      - biblivre-db:/var/lib/postgresql/9.6/main
      - ./webapps:/usr/local/tomcat/webapps
    restart: unless-stopped

volumes:
  biblivre-db:
